#! usr/bin/env node
import { input, select } from "@inquirer/prompts";
import chalk from "chalk";
console.log(chalk.bgGreenBright("  *** Welcome to currency converter generated by Syeda Ashna Ghazanfar ***  "));
let mainCurrency = {
    "USD": 1,
    "EUR": 0.9,
    "SAR": 3.7,
    "INR": 83.6,
    "PKR": 278,
    "BHD": 0.3,
    "AED": 3.6,
};
let message1 = await select({
    message: "Select the currency to convert from:",
    choices: [{ value: "USD" }, { value: "EUR" }, { value: "SAR" }, { value: "INR" }, { value: "PKR" }, { value: "BHD" }, { value: "AED" }]
});
let message2 = await select({
    message: "Select the currency to convert to:",
    choices: [{ value: "USD" }, { value: "EUR" }, { value: "SAR" }, { value: "INR" }, { value: "PKR" }, { value: "BHD" }, { value: "AED" }]
});
let message3 = await input({
    message: "Please enter the amount you want to convert to:"
});
if (message1 === message2) {
    console.log(chalk.red("You selected same currency to convert to!,try selecting different one to proceed further.."));
}
else {
    let fromAmount = mainCurrency[message1];
    let toAmount = mainCurrency[message2];
    let amount = message3;
    let exchangeRate = amount / fromAmount; //base amount yani jo amount humne dali woh jo amount humne select ki thi usse divide krke exchange rate mille ga 
    let finalAmount = exchangeRate * toAmount; // yaha pr exchange rate se humara selected amount multiply hogi
    console.log(chalk.blue("Here is the estimated amount : "));
    console.log(Math.round(finalAmount)); //math round is used for rounding off decimals
}
;
